name: Test Docker images (on PR)

on:
  pull_request:
    paths:
      # Run only when DockerFile files are modified
      - "docker/**"

jobs:
  get_changed_files:
    name: "Build all modified docker images"
    runs-on: ubuntu-latest
    outputs:
      docker-matrix: ''
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out code
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@3f54ebb830831fc121d3263c1857cfbdc310cdb9 #v42
        with:
          files: docker/**
      - name: Run step if only the files listed above change
        if: steps.changed-files.outputs.any_changed == 'true'
        id: set-variable
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files}}
        run: |
          for file in ${CHANGED_FILES}; do
            echo "$file was changed"
          done 
          echo "docker-matrix=${CHANGED_FILES}" >> ${GITHUB_OUTPUT}
  build_modified_files:
    needs: get_changed_files
    name: Build Docker images on modified files
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.get_changed_files.outputs.docker-matrix) }} != ''
    strategy:
      matrix:
        docker-file: ${{ fromJSON(needs.get_changed_files.outputs.docker-matrix) }} # https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.docker-file }}
          push: False
